var searchData=
[
  ['bcs_2ehpp_0',['bcs.hpp',['../bcs_8hpp.html',1,'']]],
  ['beryllium_5f11_1',['beryllium_11',['../structtriumf_1_1bnmr_1_1nuclei_1_1beryllium__11.html',1,'triumf::bnmr::nuclei']]],
  ['beta_2',['beta',['../classtriumf_1_1bnmr_1_1srf_1_1nonlocal_1_1DepthResolvedAnalyzer.html#a1a9967fadf57978c0dd8f7edab37d9d3',1,'triumf::bnmr::srf::nonlocal::DepthResolvedAnalyzer::beta()'],['../classtriumf_1_1bnmr_1_1srf_1_1local_1_1DepthResolvedAnalyzer.html#a0305287b6a2e55be1264de0e0213895d',1,'triumf::bnmr::srf::local::DepthResolvedAnalyzer::beta()']]],
  ['bohr_5fmagneton_3',['Bohr_magneton',['../structtriumf_1_1constants_1_1codata__2006_1_1Bohr__magneton.html',1,'triumf::constants::codata_2006::Bohr_magneton&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2010_1_1Bohr__magneton.html',1,'triumf::constants::codata_2010::Bohr_magneton&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2014_1_1Bohr__magneton.html',1,'triumf::constants::codata_2014::Bohr_magneton&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2018_1_1Bohr__magneton.html',1,'triumf::constants::codata_2018::Bohr_magneton&lt; T &gt;']]],
  ['bohr_5fmagneton_5fin_5fev_5ft_4',['Bohr_magneton_in_eV_T',['../structtriumf_1_1constants_1_1codata__2006_1_1Bohr__magneton__in__eV__T.html',1,'triumf::constants::codata_2006::Bohr_magneton_in_eV_T&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2010_1_1Bohr__magneton__in__eV__T.html',1,'triumf::constants::codata_2010::Bohr_magneton_in_eV_T&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2014_1_1Bohr__magneton__in__eV__T.html',1,'triumf::constants::codata_2014::Bohr_magneton_in_eV_T&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2018_1_1Bohr__magneton__in__eV__T.html',1,'triumf::constants::codata_2018::Bohr_magneton_in_eV_T&lt; T &gt;']]],
  ['bohr_5fmagneton_5fin_5fhz_5ft_5',['Bohr_magneton_in_Hz_T',['../structtriumf_1_1constants_1_1codata__2006_1_1Bohr__magneton__in__Hz__T.html',1,'triumf::constants::codata_2006::Bohr_magneton_in_Hz_T&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2010_1_1Bohr__magneton__in__Hz__T.html',1,'triumf::constants::codata_2010::Bohr_magneton_in_Hz_T&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2014_1_1Bohr__magneton__in__Hz__T.html',1,'triumf::constants::codata_2014::Bohr_magneton_in_Hz_T&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2018_1_1Bohr__magneton__in__Hz__T.html',1,'triumf::constants::codata_2018::Bohr_magneton_in_Hz_T&lt; T &gt;']]],
  ['bohr_5fmagneton_5fin_5finverse_5fmeter_5fper_5ftesla_6',['Bohr_magneton_in_inverse_meter_per_tesla',['../structtriumf_1_1constants_1_1codata__2018_1_1Bohr__magneton__in__inverse__meter__per__tesla.html',1,'triumf::constants::codata_2018']]],
  ['bohr_5fmagneton_5fin_5finverse_5fmeters_5fper_5ftesla_7',['Bohr_magneton_in_inverse_meters_per_tesla',['../structtriumf_1_1constants_1_1codata__2006_1_1Bohr__magneton__in__inverse__meters__per__tesla.html',1,'triumf::constants::codata_2006::Bohr_magneton_in_inverse_meters_per_tesla&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2010_1_1Bohr__magneton__in__inverse__meters__per__tesla.html',1,'triumf::constants::codata_2010::Bohr_magneton_in_inverse_meters_per_tesla&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2014_1_1Bohr__magneton__in__inverse__meters__per__tesla.html',1,'triumf::constants::codata_2014::Bohr_magneton_in_inverse_meters_per_tesla&lt; T &gt;']]],
  ['bohr_5fmagneton_5fin_5fk_5ft_8',['Bohr_magneton_in_K_T',['../structtriumf_1_1constants_1_1codata__2006_1_1Bohr__magneton__in__K__T.html',1,'triumf::constants::codata_2006::Bohr_magneton_in_K_T&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2010_1_1Bohr__magneton__in__K__T.html',1,'triumf::constants::codata_2010::Bohr_magneton_in_K_T&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2014_1_1Bohr__magneton__in__K__T.html',1,'triumf::constants::codata_2014::Bohr_magneton_in_K_T&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2018_1_1Bohr__magneton__in__K__T.html',1,'triumf::constants::codata_2018::Bohr_magneton_in_K_T&lt; T &gt;']]],
  ['bohr_5fradius_9',['Bohr_radius',['../structtriumf_1_1constants_1_1codata__2006_1_1Bohr__radius.html',1,'triumf::constants::codata_2006::Bohr_radius&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2010_1_1Bohr__radius.html',1,'triumf::constants::codata_2010::Bohr_radius&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2014_1_1Bohr__radius.html',1,'triumf::constants::codata_2014::Bohr_radius&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2018_1_1Bohr__radius.html',1,'triumf::constants::codata_2018::Bohr_radius&lt; T &gt;']]],
  ['boltzmann_5fconstant_10',['Boltzmann_constant',['../structtriumf_1_1constants_1_1codata__2006_1_1Boltzmann__constant.html',1,'triumf::constants::codata_2006::Boltzmann_constant&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2010_1_1Boltzmann__constant.html',1,'triumf::constants::codata_2010::Boltzmann_constant&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2014_1_1Boltzmann__constant.html',1,'triumf::constants::codata_2014::Boltzmann_constant&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2018_1_1Boltzmann__constant.html',1,'triumf::constants::codata_2018::Boltzmann_constant&lt; T &gt;']]],
  ['boltzmann_5fconstant_5fin_5fev_5fk_11',['Boltzmann_constant_in_eV_K',['../structtriumf_1_1constants_1_1codata__2006_1_1Boltzmann__constant__in__eV__K.html',1,'triumf::constants::codata_2006::Boltzmann_constant_in_eV_K&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2010_1_1Boltzmann__constant__in__eV__K.html',1,'triumf::constants::codata_2010::Boltzmann_constant_in_eV_K&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2014_1_1Boltzmann__constant__in__eV__K.html',1,'triumf::constants::codata_2014::Boltzmann_constant_in_eV_K&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2018_1_1Boltzmann__constant__in__eV__K.html',1,'triumf::constants::codata_2018::Boltzmann_constant_in_eV_K&lt; T &gt;']]],
  ['boltzmann_5fconstant_5fin_5fhz_5fk_12',['Boltzmann_constant_in_Hz_K',['../structtriumf_1_1constants_1_1codata__2006_1_1Boltzmann__constant__in__Hz__K.html',1,'triumf::constants::codata_2006::Boltzmann_constant_in_Hz_K&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2010_1_1Boltzmann__constant__in__Hz__K.html',1,'triumf::constants::codata_2010::Boltzmann_constant_in_Hz_K&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2014_1_1Boltzmann__constant__in__Hz__K.html',1,'triumf::constants::codata_2014::Boltzmann_constant_in_Hz_K&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2018_1_1Boltzmann__constant__in__Hz__K.html',1,'triumf::constants::codata_2018::Boltzmann_constant_in_Hz_K&lt; T &gt;']]],
  ['boltzmann_5fconstant_5fin_5finverse_5fmeter_5fper_5fkelvin_13',['Boltzmann_constant_in_inverse_meter_per_kelvin',['../structtriumf_1_1constants_1_1codata__2018_1_1Boltzmann__constant__in__inverse__meter__per__kelvin.html',1,'triumf::constants::codata_2018']]],
  ['boltzmann_5fconstant_5fin_5finverse_5fmeters_5fper_5fkelvin_14',['Boltzmann_constant_in_inverse_meters_per_kelvin',['../structtriumf_1_1constants_1_1codata__2006_1_1Boltzmann__constant__in__inverse__meters__per__kelvin.html',1,'triumf::constants::codata_2006::Boltzmann_constant_in_inverse_meters_per_kelvin&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2010_1_1Boltzmann__constant__in__inverse__meters__per__kelvin.html',1,'triumf::constants::codata_2010::Boltzmann_constant_in_inverse_meters_per_kelvin&lt; T &gt;'],['../structtriumf_1_1constants_1_1codata__2014_1_1Boltzmann__constant__in__inverse__meters__per__kelvin.html',1,'triumf::constants::codata_2014::Boltzmann_constant_in_inverse_meters_per_kelvin&lt; T &gt;']]],
  ['boron_5f12_15',['boron_12',['../structtriumf_1_1bnmr_1_1nuclei_1_1boron__12.html',1,'triumf::bnmr::nuclei']]]
];
